sudo: false

install:
  - wget http://www.vtk.org/files/release/7.0/VTK-7.0.0.tar.gz
  - tar -xf VTK-7.0.0.tar.gz
  - mkdir VTKBin && cd VTKBin && cmake ../VTK-7.0.0 -DCMAKE_BUILD_TYPE=Release

language: cpp
cache: ccache

script: cmake . -DVTK_DIR=$HOME/VTKBin -DCMAKE_BUILD_TYPE=Release  && make
